### ISSUE TITLE
평가완료후

### ISSUE THREAD

**Issue by ravieeeee** [quarl894/Firebase_exam#30]
평가하기 완료하고 내 영수증 리스트 가보면 비어있음

**Comment by quarl894** [comment]
메인에서 영수증 받을때 2번 연속 받는듯. 그리고 uidset이 무슨용도인지 잘 모르겠음.

**Comment by ravieeeee** [comment]
ㅇㅎ 봐볼게

**Comment by ravieeeee** [comment]
고침 근데 평가하기 완료하고 영수증 리스트 가보는건 영수증 3개라그런지 검은화면때문에 못봄

**Comment by ridickle7** [comment]
요거 아직 수정 안된거라면..!

ReceiptFragment 82번째 줄에서
} else if (myRequestReceipt.size() > numUid) 를 
} else if (myRequestReceipt.size() >= numUid) 로 바꾸면 되지 않을까 싶너요

numUid가 혹시 어떤 역할을 하는지 알 수 있을까요?

**Comment by ravieeeee** [comment]
한달전에 해놔서 기억이 안나네요 크흡,,, 그냥 numUid 체킹 안해봤는데 잘 되는거같아요! 
근데 #31 이 버그때문에 확인은 못하고있어요ㅠ 시간되시면 의뢰 데이터좀 쌓아주시면 감사할거같습니다!!!

**Comment by ridickle7** [comment]
최선을 다해서!
