### ISSUE TITLE
의뢰하기 금액

### ISSUE THREAD

**Issue by ravieeeee** [quarl894/Firebase_exam#34]
50억 써봤더니 앱 죽음
data type 때문 아닐까 싶음

**Comment by ridickle7** [comment]
그거 xml 내에서 maxLength 로 자리수 설정해주면 에러 안나요~~

android:maxLength="3" <-- 3자리수까지 입력됨

**Comment by ravieeeee** [comment]
아하 글쿤요!!!
감사합니다😀

**Comment by ravieeeee** [comment]
@ridickle7 그럼 몇자리수로 하는게 좋을까요?? 기획에서 정해야하는 것 같기두 하고 그러네요

**Comment by ridickle7** [comment]
뭐 그냥 카톡에 물어보면 괜찮을 것 같기도 하네요 ㅋㅋㅋ

**Comment by ravieeeee** [comment]
https://github.com/quarl894/Firebase_exam/commit/fe68cd14af1cf422a4d0f6421acc5c1205f28ae4
해결!
